services:
  clash:
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ./config/clash_config.yaml:/root/.config/clash/config.yaml
 
    restart: unless-stopped
    networks:
      - wrapper_net 


  url-wrapper:
    container_name: url-wrapper
    build: 
      context: .
      dockerfile: Dockerfile 

    ports:
      - "8085:8085"
    networks:
      - wrapper_net
    depends_on:
      - clash
      

  
networks:
  wrapper_net:
    



    